const characters = [
  "Harry Potter",
  "Sherlock Holmes",
  "Batman",
  "Bluey",
  "Spiderman",
  "Vaiana",
  "Mickey Mouse",
  "Pato Donald",
  "Pato Lucas",
  "Bugs Bunny",
  "Goofy",
  "Daisy",
  "Minnie Mouse",
  "Peter Pan",
  "Luca",
  "David el Gnomo",
  "He-Man",
  "Mulán",
  "Cruela de Vil",
  "Maui",
  "Pinocho",
  "Capitán Garfio",
  "Pepa Pig",
  "Dora la Exploradora",
  "Bob Esponja",
  "Patricio",
  "Calamardo",
  "Buzz Lightyear",
  "Woody",
  "Tadeo Jones",
  "Indiana Jones",
  "Elsa",
  "Olaf",
  "PocaHontas",
  "Tarzán",
  "Simba",
  "Nemo",
  "Dory",
  "Aladdin",
  "Jazmín",
  "Genio",
  "Ariel",
  "Blancanieves",
  "Cenicienta",
  "Maléfica",
  "Hulk",
  "Thor",
  "IronMan",
  "Capitán América",
  "Darth Vader",
  "Yoda",
  "R2D2",
  "C3PO",
  "Luke Skywalker",
  "Chewbacca",
  "Garfield",
  "Snoopy",
  "Pitufina",
  "Pitufo Filósofo",
  "Pitufo Gruñón",
  "SuperMan",
  "WonderWoman",
  "Flash",
  "Aquaman",
  "Son Goku",
  "Vegeta",
  "Naruto",
  "Sonic",
  "Mario",
  "Luigi",
  "Pikachu",
  "Zelda",
  "Link",
  "Kirby",
  "Donkey Kong",
  "Yoshi",
  "Bowser",
  "Peach",
  "Gandalf",
  "Frodo",
  "Gollum",
  "Mary Poppins",
  "Scooby Doo",
  "Pedro Picapiedra",
  "La Pantera Rosa",
  "Inspector Gadget",
  "Mortadelo",
  "Filemón",
  "Zipi",
  "Zape",
  "Super López",
  "Tintín",
  "Capitán Haddock",
  "Milú",
  "Obélix",
  "Astérix",
  "Idefix",
  "Cleopatra",
  "Julio César",
  "Pirata Barbanegra",
  "Monkey D. Luffy",
  "Mandalorian",
  "Baby Yoda",
  "Mazinger Z",
  "Caballero del Pegaso",
  "Donatello",
  "Leonardo",
  "Michelangelo",
  "Despedazador",
  "Watson",
  "Drácula",
  "Frankenstein",
  "El Jorobado de Notre Dame",
  "El Zorro",
  "El Gato con Botas",
  "El Rey Arturo",
  "Merlín",
  "Robin Hood",
  "Poseidón",
  "Zeus",
  "Hércules",
];

export default characters;
