const professions = [
  "Médico",
  "Ingeniero",
  "Abogado",
  "Arquitecto",
  "Profesor",
  "Piloto",
  "Chef",
  "Periodista",
  "Programador",
  "Diseñador gráfico",
  "Psicólogo",
  "Veterinario",
  "Fotógrafo",
  "Actor",
  "Músico",
  "Bombero",
  "Policía",
  "Soldado",
  "Astronauta",
  "Biólogo",
  "Químico",
  "Físico",
  "Matemático",
  "Economista",
  "Sociólogo",
  "Historiador",
  "Geólogo",
  "Meteorólogo",
  "Oceanógrafo",
  "Arqueólogo"
];

export default professions;